[tools]
lefthook = "latest"
node = "lts"
pnpm = "latest"

[tasks]
format = "pnpm run format"
lint = "pnpm run lint"
type-check = "pnpm run type-check"
build = "pnpm run build"
deploy = "pnpm run deploy"
db-setup = "docker-compose up -d libsql-server && pnpm run db:migrate"
dev = "docker compose up -d"
