services:
  app:
    build: .
    ports:
      - '5173:5173'
    volumes:
      - .:/app:cached
      - /app/node_modules
    environment:
      - TURSO_AUTH_TOKEN=dev-token
    depends_on:
      - libsql-server
    command: sh -c "TURSO_DATABASE_URL=http://libsql-server:8080; pnpm db:push && pnpm dev --host"

  libsql-server:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - '8080:8080'
    environment:
      - SQLE_HTTP_URL=http://0.0.0.0:8080
    volumes:
      - libsql-data:/var/lib/sqld

volumes:
  libsql-data:
